# Generated by Django 4.0.4 on 2022-06-02 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('budget', models.FloatField()),
            ],
            options={
                'db_table': 'budget',
                'managed': True,
            },
        ),
    ]
